import BOMBER1 from './assets/images/BOMBER1.png';
import BOMBER2 from './assets/images/BOMBER2.png';
import BOMBER1501 from './assets/images/BOMBER1501.png';
import BOMBER1502 from './assets/images/BOMBER1502.jpg';
import BOMBERSP1 from './assets/images/BOMBERSP1.png';
import BOMBERSP2 from './assets/images/BOMBERSP2.png';
import NITRO1251 from './assets/images/NITRO1251.png';
import NITRO1252 from './assets/images/NITRO1252.png';
import ONEST1 from './assets/images/ONEST1.png';
import ONEST2 from './assets/images/ONEST2.png';
import SWITCH1501 from './assets/images/SWITCH1501.png';
import SWITCH1502 from './assets/images/SWITCH1502.png';
import VENOM4001 from './assets/images/VENOM4001.png';
import VENOM4002 from './assets/images/VENOM4002.png';
import LIFE1 from './assets/images/LIFE1.jpg';
import LIFE2 from './assets/images/LIFE2.jpg';
import BOLD1 from './assets/images/BOLD1.jpg';
import BOLD2 from './assets/images/BOLD2.jpg';
import BOLDPRO1 from './assets/images/BOLDPRO1.jpg';
import BOLDPRO2 from './assets/images/BOLDPRO2.jpg';
import NEWPRO1 from './assets/images/NEWPRO1.jpg';
import NEWPRO2 from './assets/images/NEWPRO2.jpg';
import LEONCINO1 from './assets/images/LEONCINO1.jpg';
import LEONCINO2 from './assets/images/LEONCINO2.jpg';
import IMPERIABLE1 from './assets/images/IMPERIABLE1.jpg';
import IMPERIABLE2 from './assets/images/IMPERIABLE2.jpg';

export default {
  AutomaticMotorcycles: [
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/BqR6Yvb/automatica1.png',
      name: 'LIFE',
      price: '6.199.000',
      description:
        'Llegó la scooter full equipo con más espacio, que te empodera para que puedas vivir más y mejores experiencias de vida alcanzando tus sueños.',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '124,6 CC',
      maximum_power: '8.4 HP @ 7500 rpm',
      refrigeration: 'Aire forzado',
      transmission: 'Automática centrífuga (CVT)',
      gas: 'Gasolina corriente',
      front_brake: 'Disco, pinza doble pistón',
      back_brake: 'Disco central',
      weight: '105 kg',
      img1: LIFE1,
      img2: LIFE2,
    },
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/vmj2mT5/automatica2.png',
      name: 'BOLD',
      price: '7.199.000',
      description:
        'Una scooter con luces asimétricas, robusta y más altura que las demás, la hace ideal para tus necesidades.',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '124,6 CC',
      maximum_power: '8.7 HP @ 7000 rpm',
      refrigeration: 'Aire forzado',
      transmission: 'Automática centrífuga (CVT)',
      gas: 'Gasolina corriente',
      front_brake: 'Disco (240 mm) Mordaza doble pistón',
      back_brake: 'Campana (130 mm)',
      weight: '121 kg',
      img1: BOLD1,
      img2: BOLD2,
    },
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/3djL6jS/automatica3.png',
      name: 'BOLD PRO',
      price: '7.499.000',
      description:
        'Una scooter con luces asimétricas, robusta y más altura que las demás, la hace ideal para tus necesidades.',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '124,6 CC',
      maximum_power: '8.7 HP @ 7000 rpm',
      refrigeration: 'Aire forzado',
      transmission: 'Automática centrífuga (CVT)',
      gas: 'Gasolina corriente',
      front_brake: 'Disco (240 mm) Mordaza doble pistón',
      back_brake: 'Campana (130 mm)',
      weight: '121 kg',
      img1: BOLDPRO1,
      img2: BOLDPRO2,
    },
    {
      line: 'KYMCO',
      url_image: 'https://i.ibb.co/k34FS6j/automatica4.png',
      name: 'AGILITY FUSION',
      price: '8.499.000',
      description:
        'La scooter deportiva con la maniobralidad ideal para que recorras la ciudad con total confianza y seguridad.',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '124,6 CC',
      maximum_power: '9.3 HP @ 7000 rpm',
      refrigeration: 'Aire forzado',
      transmission: 'Automática centrífuga (CVT)',
      gas: 'Gasolina corriente',
      front_brake: 'Disco (200 mm) Mordaza doble pistón',
      back_brake: 'Tambor 130 mm',
      weight: '116 kg',
      img1: null,
      img2: null,
    },
    {
      line: 'KYMCO',
      url_image: 'https://i.ibb.co/wNVqP51/automatica5.png',
      name: 'AGILITY ALL NEW PRO',
      price: '9.999.000',
      description:
        'El icónico modelo de la marca Kymco, se renovó para traerte todo un universo diferente y un estilo mejorado.',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '124,6 CC',
      maximum_power: '9.5 HP @ 7500 rpm',
      refrigeration: 'Aire forzado',
      transmission: 'Automática centrífuga (CVT)',
      gas: 'Gasolina corriente',
      front_brake: 'Disco (220 mm) Mordaza doble pistón',
      back_brake: 'Tambor 130 mm',
      weight: '119 kg',
      img1: NEWPRO1,
      img2: NEWPRO2,
    },
    {
      line: 'KYMCO',
      url_image: 'https://i.ibb.co/NWF3v1d/automatica6.png',
      name: 'SUPER 8',
      price: '13.499.000',
      description:
        'Ilumina tu camino y llega de manera ágil a donde quieras, la nueva KYMCO SUPER 8 es para aquellos que el día a día no los deja descansar.',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '149,4 CC',
      maximum_power: '10.3 HP @ 7500 rpm',
      refrigeration: 'Aire forzado',
      transmission: 'Automática centrífuga (CVT)',
      gas: 'Gasolina corriente',
      front_brake: 'Disco (220 mm) Mordaza doble pistón',
      back_brake: 'Tambor 130 mm',
      weight: '121 kg',
      img1: null,
      img2: null,
    },
  ],
  SportMotorcycles: [
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/k4NVjy6/urbana6.png',
      name: 'SWITCH 150',
      description:
        'Su potente motor y su pequeño tamaño te harán disfrutar sin límites. Una pequeña gigante con tantos atributos que la destacan en el mercado, hará que marques la diferencia.',
      price: '6.799.000',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '149,2 CC',
      maximum_power: '12 HP @ 8000 rpm',
      refrigeration: 'Aire',
      transmission: 'Mecánica 5 velocidades',
      gas: 'Gasolina corriente',
      front_brake: 'Disco 220 mm',
      back_brake: 'Disco 170 mm',
      weight: '105,2 kg',
      img1: SWITCH1501,
      img2: SWITCH1502,
    },
    {
      line: 'BENELLI',
      url_image: ' https://i.ibb.co/vPwRyfy/deportiva2.png',
      name: 'BENELLI 180S',
      description:
        'Te bastará una mirada a la agresiva postura de la nueva Benelli 180S y una minuciosa inspección a sus componentes para darte cuenta del diseño italiano que lleva en su sangre.',
      price: '10.299.000',
      engine: 'Monocilíndrico 4 tiempos 4 válvulas SOHC',
      cylinder: '175 CC',
      maximum_power: '18 HP @ 9500 rpm',
      refrigeration: 'Líquido',
      transmission: 'Mecánica 6 velocidades',
      gas: 'Gasolina extra',
      front_brake: 'Doble Disco 300 mm, doble mordaza de 4 pistones',
      back_brake: 'Disco 260 mm, mordaza de un pistón',
      weight: '140 kg',
      img1: null,
      img2: null,
    },
    {
      line: 'BENELLI',
      url_image: 'https://i.ibb.co/GvjpsPx/deportiva3.png',
      name: 'BENELLI 180S PRO X',
      description:
        'Con la nueva edición limitada de la 180 S PRO X bastará con una mirada a la agresiva postura de la nueva Benelli 180S y una minuciosa inspección a sus componentes para darte cuenta del diseño italiano que lleva en su sangre.',
      price: '10.799.000',
      engine: 'Monocilíndrico 4 tiempos 4 válvulas SOHC',
      cylinder: '175 CC',
      maximum_power: '18 HP @ 9500 rpm',
      refrigeration: 'Líquido',
      transmission: 'Mecánica 6 velocidades',
      gas: 'Gasolina extra',
      front_brake: 'Doble Disco 300 mm, doble mordaza de 4 pistones',
      back_brake: 'Disco 260 mm, mordaza de un pistón',
      weight: '140 kg',
      img1: null,
      img2: null,
    },
    {
      line: 'KAWASAKI',
      url_image: 'https://i.ibb.co/2KvbR6m/deportiva4.png',
      name: 'NINJA 400',
      description: 'Nacida para la calle inspirada para la pista.',
      price: '31.990.000',
      engine: '4 tiempos, bicilíndrico en paralelo',
      cylinder: '399 cc',
      maximum_power: '44.8 HP @ 10000 rpm',
      refrigeration: 'Líquido',
      transmission: 'Mecánica 6 velocidades',
      gas: 'Gasolina extra',
      front_brake: 'Doble Disco 300 mm, doble mordaza de 4 pistones',
      back_brake: 'Disco 260 mm, mordaza de un pistón',
      weight: '168 kg',
      img1: null,
      img2: null,
    },
    {
      line: 'BENELLI',
      url_image: 'https://i.ibb.co/yFqnCc1/deportiva5.png',
      name: 'BENELLI TNT 25N',
      description:
        'Una naked que resalta en diseño italiano, por el amor a los detalles. Está impulsada por un ligero y potente motor monocilíndrico de cuatro tiempos de 249 cc.',
      price: '12.499.000',
      engine: 'Monocilíndrico 4 tiempos 4 válvulas DOHC',
      cylinder: '249 cc',
      maximum_power: '25,8 HP @ 9250 rpm',
      refrigeration: 'Líquido',
      transmission: 'Mecánica 6 velocidades',
      gas: 'Gasolina extra',
      front_brake: 'Disco flotante de 280 mm con mordaza de 4 pistones',
      back_brake: 'Disco de 240 mm',
      weight: '146 kg',
      img1: null,
      img2: null,
    },
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/VNSR9pH/deportiva6.png',
      name: 'VENOM 400',
      description:
        'Esta línea representa lo mejor de lo mejor de Victory. Así es que cada vez que veas el emblema BlackLine en una de nuestras motocicletas, sabrás que estás frente una digna representante de una serie de motos inspirada en la excelencia.',
      price: '19.490.000',
      engine: 'Bicilíndrico en paralelo, 4t SOHC, 8 válvulas',
      cylinder: '378 cc',
      maximum_power: '36.2 HP @ 9000 rpm',
      refrigeration: 'Líquido',
      transmission: 'Mecánica',
      gas: 'Gasolina extra',
      front_brake: 'Doble Disco 300 mm, doble mordaza de 4 pistones',
      back_brake: 'Disco 260 mm, mordaza de un pistón',
      weight: '175 kg',
      img1: VENOM4001,
      img2: VENOM4002,
    },
  ],
  UrbanMotorcycles: [
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/DDmc1s2/urbana1.png',
      name: 'ONE ST 110',
      description:
        'Una moto que no le hace falta nada, reuniendo tecnologías que te brindan comodidad en todo momento para que te enamores de ella.',
      price: '4.399.000',
      engine: '4 tiempos, monocilíndrico',
      cylinder: '109 cc',
      maximum_power: '8HP @ 7500 rpm',
      refrigeration: 'Aire',
      transmission: 'Mecánica 4 velocidades',
      gas: 'Gasolina corriente',
      front_brake: 'Disco 240 mm, Mordaza de 2 pistones',
      back_brake: 'Campana 130 mm',
      weight: '108 kg',
      img1: ONEST1,
      img2: ONEST2,
    },
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/pvPTyT5/urbana2.png',
      name: 'BOMBER 125',
      description:
        'Las mejores tecnologías en motores son implementadas en este modelo, siendo así también responsables con el medio ambiente.',
      price: '4.999.000',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '124 CC',
      maximum_power: '10,72 HP @ 9000 rpm',
      refrigeration: 'Aire',
      transmission: 'Mecánica 4 velocidades',
      gas: 'Gasolina corriente',
      front_brake: 'Disco de 240 mm',
      back_brake: 'Tambor de 130 mm',
      weight: '105 kg',
      img1: BOMBER1,
      img2: BOMBER2,
    },
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/fr0JY7r/urbana3.png',
      name: 'BOMBER 125 SPORT',
      description:
        'Su potencia máxima es de 10,7 HP @ 9000 rpm, esto la caracteriza como la Café Racer 125 más potente de Colombia.',
      price: '5.349.000',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '124 CC',
      maximum_power: '10,72 HP @ 9000 rpm',
      refrigeration: 'Aire',
      transmission: 'Mecánica 5 velocidades',
      gas: 'Gasolina corriente',
      front_brake: 'Disco de 240 mm',
      back_brake: 'Tambor de 130 mm',
      weight: '105 kg',
      img1: BOMBERSP1,
      img2: BOMBERSP2,
    },
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/d48hdXG/urbana4.png',
      name: 'BOMBER 150',
      description:
        'Un estilo definido evocando las mejores épocas del motociclismo pero con tecnologías a la vanguardia.',
      price: '5.999.000',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '149,4 CC',
      maximum_power: '12,7 HP @ 8500 rpm',
      refrigeration: 'Aire',
      transmission: 'Mecánica 5 velocidades',
      gas: 'Gasolina corriente',
      front_brake: 'Disco de 256 mm',
      back_brake: 'Campana de 130 mm',
      weight: '120 kg',
      img1: BOMBER1501,
      img2: BOMBER1502,
    },
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/WGpmDZD/urbana5.png',
      name: 'NITRO 125 PRO',
      description:
        'Transportarte en tu día a día nunca había sido tan cómodo, como cuando te mueves en una Nitro 125. Sabemos que los tiempos han cambiado y que la era digital es hoy, por eso traemos un tablero digital impactante.',
      price: '6.399.000',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '124,8 CC',
      maximum_power: '10,72 HP @ 8500 rpm',
      refrigeration: 'Aire',
      transmission: 'Mecánica 5 velocidades',
      gas: 'Gasolina corriente',
      front_brake: 'Disco delantero lobulado 240 mm',
      back_brake: 'Tambor 130 mm',
      weight: '120 kg',
      img1: NITRO1251,
      img2: NITRO1252,
    },
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/k4NVjy6/urbana6.png',
      name: 'SWITCH 150',
      description:
        'Su potente motor y su pequeño tamaño te harán disfrutar sin límites. Una pequeña gigante con tantos atributos que la destacan en el mercado, hará que marques la diferencia.',
      price: '6.799.000',
      engine: '4 Tiempos, Monocilíndrico',
      cylinder: '149,2 CC',
      maximum_power: '12 HP @ 8000 rpm',
      refrigeration: 'Aire',
      transmission: 'Mecánica 5 velocidades',
      gas: 'Gasolina corriente',
      front_brake: 'Disco 220 mm',
      back_brake: 'Disco 170 mm',
      weight: '105,2 kg',
      img1: SWITCH1501,
      img2: SWITCH1502,
    },
  ],
  HighEndMotorcycles: [
    {
      line: 'BENELLI',
      url_image: 'https://i.ibb.co/xg7chcY/altagama1.png',
      name: 'BENELLI TRK 251',
      description:
        'La mejor moto para iniciarse en el mundo touring gracias a su peso ligero y su facilidad en la conducción. Una distribución de pesos para sortear todo tipo de terrenos sin ningún problema.',
      price: '18.499.000',
      engine: 'Monocilíndrico 4 tiempos 4 válvulas DOHC',
      cylinder: '249 cc',
      maximum_power: '25,84 HP @ 9250 rpm',
      refrigeration: 'Líquido',
      transmission: 'Mecánica 6 velocidades',
      gas: 'Gasolina extra',
      front_brake: 'Doble Disco 300 mm, doble mordaza de 4 pistones',
      back_brake: 'Disco 260 mm, mordaza de un pistón',
      weight: '143 kg',
      img1: null,
      img2: null,
    },
    {
      line: 'VICTORY',
      url_image: 'https://i.ibb.co/VNSR9pH/deportiva6.png',
      name: 'VENOM 400',
      description:
        'Esta línea representa lo mejor de lo mejor de Victory. Así es que cada vez que veas el emblema BlackLine en una de nuestras motocicletas, sabrás que estás frente una digna representante de una serie de motos inspirada en la excelencia.',
      price: '19.490.000',
      engine: 'Bicilíndrico en paralelo, 4t SOHC, 8 válvulas',
      cylinder: '378 cc',
      maximum_power: '36.2 HP @ 9000 rpm',
      refrigeration: 'Líquido',
      transmission: 'Mecánica',
      gas: 'Gasolina extra',
      front_brake: 'Doble Disco 300 mm, doble mordaza de 4 pistones',
      back_brake: 'Disco 260 mm, mordaza de un pistón',
      weight: '175 kg',
      img1: VENOM4001,
      img2: VENOM4002,
    },
    {
      line: 'BENELLI',
      url_image: 'https://i.ibb.co/xqfqnGF/altagama3.png',
      name: 'BENELLI IMPERIALE 400',
      description:
        'Un clásico que revive los más de 100 años de historia de Benelli gracias a la Imperiale 400. Un motor monocilíndrico refrigerado por aire de 4 tiempos. Una potencia de 21,1 Hp @ 5500 rpm, haciendo que la conducción sea suave. Sus ruedas compuestas por llantas de radios de 19 delante y 18 detrás, generan una sensación de manejo tranquila y cómoda.',
      price: '20.990.000',
      engine: '4 Tiempos, monocilindrico de 2 válvulas',
      cylinder: '374 cc',
      maximum_power: '21,1 HP @ 5500 rpm',
      refrigeration: 'Aire',
      transmission: 'Mecánica 5 velocidades',
      gas: 'Gasolina corriente',
      front_brake: 'Doble Disco 300 mm, doble mordaza de 4 pistones',
      back_brake: 'Disco 260 mm, mordaza de un pistón',
      weight: '184 kg',
      img1: IMPERIABLE1,
      img2: IMPERIABLE2,
    },
    {
      line: 'BENELLI',
      url_image: 'https://i.ibb.co/p4D5CF4/altagama4.png',
      name: 'BENELLI LEONCINO 500',
      description:
        'El nombre de “Leoncino” es el homenaje a una leyenda del motociclismo italiano que ha hecho historia en Benelli. La Leoncino no es sólo un nuevo modelo, sino un concepto auténtico y puro, típicamente italiano. Su corazón está formado por el motor bicilíndrico de 500cc de cuatro tiempos y cuatro válvulas por cilindro, doble árbol de levas en cabeza (DOHC) refrigerado por líquido.',
      price: '31.499.0000',
      engine: 'Bicilíndrico, 4 tiempos, 8 válvulas DOHC',
      cylinder: '500 cc',
      maximum_power: '47,6 HP @ 8500 rpm',
      refrigeration: 'Líquido',
      transmission: 'Mecánica 6 velocidades',
      gas: 'Gasolina extra',
      front_brake: 'Doble Disco 300 mm, doble mordaza de 4 pistones',
      back_brake: 'Disco 260 mm, mordaza de un pistón',
      weight: '198 kg',
      img1: LEONCINO1,
      img2: LEONCINO2,
    },
    {
      line: 'KAWASAKI',
      url_image: 'https://i.ibb.co/2KvbR6m/deportiva4.png',
      name: 'NINJA 400',
      description: 'Nacida para la calle inspirada para la pista.',
      price: '31.990.000',
      engine: '4 tiempos, bicilíndrico en paralelo',
      cylinder: '399 cc',
      maximum_power: '44.8 HP @ 10000 rpm',
      refrigeration: 'Líquido',
      transmission: 'Mecánica 6 velocidades',
      gas: 'Gasolina extra',
      front_brake: 'Doble Disco 300 mm, doble mordaza de 4 pistones',
      back_brake: 'Disco 260 mm, mordaza de un pistón',
      weight: '168 kg',
      img1: null,
      img2: null,
    },
    {
      line: 'KAWASAKI',
      url_image: 'https://i.ibb.co/vBbqQd0/altagama6.png',
      name: 'Z400',
      description:
        'CREADA PARA SER VISTA La ‘nueva escuela’ recibe un nuevo contendiente con la llegada de la ligera motocicleta Kawasaki Z400 ABS. Feroz al descubierto, la Z400 ABS irradia un estilo callejero fresco y se reconoce fácilmente entre la multitud con su chasis compacto y su estilo agresivo. Cómoda, equilibrada y capacitada, la nueva Z400 ABS ofrece una experiencia de conducción emocionante que, sin duda, captará miradas.',
      price: '31.990.000',
      engine: 'Bicilíndrico, 4 tiempos, 8 válvulas DOHC',
      cylinder: '500 cc',
      maximum_power: '47,6 HP @ 8500 rpm',
      refrigeration: 'Líquido',
      transmission: 'Mecánica 6 velocidades',
      gas: 'Gasolina extra',
      front_brake: 'Doble disco flotante de 320 mm con mordaza de 4 pistones',
      back_brake: 'Disco de 260 mm con mordaza de un pistón',
      weight: '198 kg',
      img1: null,
      img2: null,
    },
  ],
};
